# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/hsunekichi/Escritorio/videojuegos-lemmings

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/hsunekichi/Escritorio/videojuegos-lemmings

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hsunekichi/Escritorio/videojuegos-lemmings/CMakeFiles /home/hsunekichi/Escritorio/videojuegos-lemmings//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hsunekichi/Escritorio/videojuegos-lemmings/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ray

# Build rule for target.
ray: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ray
.PHONY : ray

# fast build rule for target.
ray/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray.dir/build.make CMakeFiles/ray.dir/build
.PHONY : ray/fast

#=============================================================================
# Target rules for targets named transform

# Build rule for target.
transform: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 transform
.PHONY : transform

# fast build rule for target.
transform/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/transform.dir/build.make CMakeFiles/transform.dir/build
.PHONY : transform/fast

#=============================================================================
# Target rules for targets named math

# Build rule for target.
math: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 math
.PHONY : math

# fast build rule for target.
math/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/math.dir/build.make CMakeFiles/math.dir/build
.PHONY : math/fast

#=============================================================================
# Target rules for targets named spectrum

# Build rule for target.
spectrum: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 spectrum
.PHONY : spectrum

# fast build rule for target.
spectrum/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spectrum.dir/build.make CMakeFiles/spectrum.dir/build
.PHONY : spectrum/fast

#=============================================================================
# Target rules for targets named texture

# Build rule for target.
texture: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 texture
.PHONY : texture

# fast build rule for target.
texture/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/texture.dir/build.make CMakeFiles/texture.dir/build
.PHONY : texture/fast

#=============================================================================
# Target rules for targets named engine

# Build rule for target.
engine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 engine
.PHONY : engine

# fast build rule for target.
engine/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/build
.PHONY : engine/fast

#=============================================================================
# Target rules for targets named entity

# Build rule for target.
entity: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 entity
.PHONY : entity

# fast build rule for target.
entity/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/entity.dir/build.make CMakeFiles/entity.dir/build
.PHONY : entity/fast

#=============================================================================
# Target rules for targets named render_2D

# Build rule for target.
render_2D: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 render_2D
.PHONY : render_2D

# fast build rule for target.
render_2D/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_2D.dir/build.make CMakeFiles/render_2D.dir/build
.PHONY : render_2D/fast

#=============================================================================
# Target rules for targets named physics

# Build rule for target.
physics: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 physics
.PHONY : physics

# fast build rule for target.
physics/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/physics.dir/build.make CMakeFiles/physics.dir/build
.PHONY : physics/fast

#=============================================================================
# Target rules for targets named game

# Build rule for target.
game: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 game
.PHONY : game

# fast build rule for target.
game/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/build
.PHONY : game/fast

#=============================================================================
# Target rules for targets named geralt_eats

# Build rule for target.
geralt_eats: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 geralt_eats
.PHONY : geralt_eats

# fast build rule for target.
geralt_eats/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/geralt_eats.dir/build.make CMakeFiles/geralt_eats.dir/build
.PHONY : geralt_eats/fast

#=============================================================================
# Target rules for targets named lemmings

# Build rule for target.
lemmings: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lemmings
.PHONY : lemmings

# fast build rule for target.
lemmings/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lemmings.dir/build.make CMakeFiles/lemmings.dir/build
.PHONY : lemmings/fast

src/engine/engine.o: src/engine/engine.cpp.o
.PHONY : src/engine/engine.o

# target to build an object file
src/engine/engine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/engine/engine.cpp.o
.PHONY : src/engine/engine.cpp.o

src/engine/engine.i: src/engine/engine.cpp.i
.PHONY : src/engine/engine.i

# target to preprocess a source file
src/engine/engine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/engine/engine.cpp.i
.PHONY : src/engine/engine.cpp.i

src/engine/engine.s: src/engine/engine.cpp.s
.PHONY : src/engine/engine.s

# target to generate assembly for a file
src/engine/engine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/src/engine/engine.cpp.s
.PHONY : src/engine/engine.cpp.s

src/engine/entity.o: src/engine/entity.cpp.o
.PHONY : src/engine/entity.o

# target to build an object file
src/engine/entity.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/entity.dir/build.make CMakeFiles/entity.dir/src/engine/entity.cpp.o
.PHONY : src/engine/entity.cpp.o

src/engine/entity.i: src/engine/entity.cpp.i
.PHONY : src/engine/entity.i

# target to preprocess a source file
src/engine/entity.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/entity.dir/build.make CMakeFiles/entity.dir/src/engine/entity.cpp.i
.PHONY : src/engine/entity.cpp.i

src/engine/entity.s: src/engine/entity.cpp.s
.PHONY : src/engine/entity.s

# target to generate assembly for a file
src/engine/entity.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/entity.dir/build.make CMakeFiles/entity.dir/src/engine/entity.cpp.s
.PHONY : src/engine/entity.cpp.s

src/engine/game.o: src/engine/game.cpp.o
.PHONY : src/engine/game.o

# target to build an object file
src/engine/game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/engine/game.cpp.o
.PHONY : src/engine/game.cpp.o

src/engine/game.i: src/engine/game.cpp.i
.PHONY : src/engine/game.i

# target to preprocess a source file
src/engine/game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/engine/game.cpp.i
.PHONY : src/engine/game.cpp.i

src/engine/game.s: src/engine/game.cpp.s
.PHONY : src/engine/game.s

# target to generate assembly for a file
src/engine/game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/engine/game.cpp.s
.PHONY : src/engine/game.cpp.s

src/engine/physics.o: src/engine/physics.cpp.o
.PHONY : src/engine/physics.o

# target to build an object file
src/engine/physics.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/physics.dir/build.make CMakeFiles/physics.dir/src/engine/physics.cpp.o
.PHONY : src/engine/physics.cpp.o

src/engine/physics.i: src/engine/physics.cpp.i
.PHONY : src/engine/physics.i

# target to preprocess a source file
src/engine/physics.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/physics.dir/build.make CMakeFiles/physics.dir/src/engine/physics.cpp.i
.PHONY : src/engine/physics.cpp.i

src/engine/physics.s: src/engine/physics.cpp.s
.PHONY : src/engine/physics.s

# target to generate assembly for a file
src/engine/physics.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/physics.dir/build.make CMakeFiles/physics.dir/src/engine/physics.cpp.s
.PHONY : src/engine/physics.cpp.s

src/engine/render_2D.o: src/engine/render_2D.cpp.o
.PHONY : src/engine/render_2D.o

# target to build an object file
src/engine/render_2D.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_2D.dir/build.make CMakeFiles/render_2D.dir/src/engine/render_2D.cpp.o
.PHONY : src/engine/render_2D.cpp.o

src/engine/render_2D.i: src/engine/render_2D.cpp.i
.PHONY : src/engine/render_2D.i

# target to preprocess a source file
src/engine/render_2D.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_2D.dir/build.make CMakeFiles/render_2D.dir/src/engine/render_2D.cpp.i
.PHONY : src/engine/render_2D.cpp.i

src/engine/render_2D.s: src/engine/render_2D.cpp.s
.PHONY : src/engine/render_2D.s

# target to generate assembly for a file
src/engine/render_2D.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/render_2D.dir/build.make CMakeFiles/render_2D.dir/src/engine/render_2D.cpp.s
.PHONY : src/engine/render_2D.cpp.s

src/geometry/ray.o: src/geometry/ray.cpp.o
.PHONY : src/geometry/ray.o

# target to build an object file
src/geometry/ray.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray.dir/build.make CMakeFiles/ray.dir/src/geometry/ray.cpp.o
.PHONY : src/geometry/ray.cpp.o

src/geometry/ray.i: src/geometry/ray.cpp.i
.PHONY : src/geometry/ray.i

# target to preprocess a source file
src/geometry/ray.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray.dir/build.make CMakeFiles/ray.dir/src/geometry/ray.cpp.i
.PHONY : src/geometry/ray.cpp.i

src/geometry/ray.s: src/geometry/ray.cpp.s
.PHONY : src/geometry/ray.s

# target to generate assembly for a file
src/geometry/ray.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray.dir/build.make CMakeFiles/ray.dir/src/geometry/ray.cpp.s
.PHONY : src/geometry/ray.cpp.s

src/geometry/transform.o: src/geometry/transform.cpp.o
.PHONY : src/geometry/transform.o

# target to build an object file
src/geometry/transform.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/transform.dir/build.make CMakeFiles/transform.dir/src/geometry/transform.cpp.o
.PHONY : src/geometry/transform.cpp.o

src/geometry/transform.i: src/geometry/transform.cpp.i
.PHONY : src/geometry/transform.i

# target to preprocess a source file
src/geometry/transform.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/transform.dir/build.make CMakeFiles/transform.dir/src/geometry/transform.cpp.i
.PHONY : src/geometry/transform.cpp.i

src/geometry/transform.s: src/geometry/transform.cpp.s
.PHONY : src/geometry/transform.s

# target to generate assembly for a file
src/geometry/transform.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/transform.dir/build.make CMakeFiles/transform.dir/src/geometry/transform.cpp.s
.PHONY : src/geometry/transform.cpp.s

src/geralt_eats/geralt_eats.o: src/geralt_eats/geralt_eats.cpp.o
.PHONY : src/geralt_eats/geralt_eats.o

# target to build an object file
src/geralt_eats/geralt_eats.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/geralt_eats.dir/build.make CMakeFiles/geralt_eats.dir/src/geralt_eats/geralt_eats.cpp.o
.PHONY : src/geralt_eats/geralt_eats.cpp.o

src/geralt_eats/geralt_eats.i: src/geralt_eats/geralt_eats.cpp.i
.PHONY : src/geralt_eats/geralt_eats.i

# target to preprocess a source file
src/geralt_eats/geralt_eats.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/geralt_eats.dir/build.make CMakeFiles/geralt_eats.dir/src/geralt_eats/geralt_eats.cpp.i
.PHONY : src/geralt_eats/geralt_eats.cpp.i

src/geralt_eats/geralt_eats.s: src/geralt_eats/geralt_eats.cpp.s
.PHONY : src/geralt_eats/geralt_eats.s

# target to generate assembly for a file
src/geralt_eats/geralt_eats.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/geralt_eats.dir/build.make CMakeFiles/geralt_eats.dir/src/geralt_eats/geralt_eats.cpp.s
.PHONY : src/geralt_eats/geralt_eats.cpp.s

src/lemmings/lemmings.o: src/lemmings/lemmings.cpp.o
.PHONY : src/lemmings/lemmings.o

# target to build an object file
src/lemmings/lemmings.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lemmings.dir/build.make CMakeFiles/lemmings.dir/src/lemmings/lemmings.cpp.o
.PHONY : src/lemmings/lemmings.cpp.o

src/lemmings/lemmings.i: src/lemmings/lemmings.cpp.i
.PHONY : src/lemmings/lemmings.i

# target to preprocess a source file
src/lemmings/lemmings.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lemmings.dir/build.make CMakeFiles/lemmings.dir/src/lemmings/lemmings.cpp.i
.PHONY : src/lemmings/lemmings.cpp.i

src/lemmings/lemmings.s: src/lemmings/lemmings.cpp.s
.PHONY : src/lemmings/lemmings.s

# target to generate assembly for a file
src/lemmings/lemmings.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lemmings.dir/build.make CMakeFiles/lemmings.dir/src/lemmings/lemmings.cpp.s
.PHONY : src/lemmings/lemmings.cpp.s

src/lib/spectrum.o: src/lib/spectrum.cpp.o
.PHONY : src/lib/spectrum.o

# target to build an object file
src/lib/spectrum.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spectrum.dir/build.make CMakeFiles/spectrum.dir/src/lib/spectrum.cpp.o
.PHONY : src/lib/spectrum.cpp.o

src/lib/spectrum.i: src/lib/spectrum.cpp.i
.PHONY : src/lib/spectrum.i

# target to preprocess a source file
src/lib/spectrum.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spectrum.dir/build.make CMakeFiles/spectrum.dir/src/lib/spectrum.cpp.i
.PHONY : src/lib/spectrum.cpp.i

src/lib/spectrum.s: src/lib/spectrum.cpp.s
.PHONY : src/lib/spectrum.s

# target to generate assembly for a file
src/lib/spectrum.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spectrum.dir/build.make CMakeFiles/spectrum.dir/src/lib/spectrum.cpp.s
.PHONY : src/lib/spectrum.cpp.s

src/lib/texture.o: src/lib/texture.cpp.o
.PHONY : src/lib/texture.o

# target to build an object file
src/lib/texture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/texture.dir/build.make CMakeFiles/texture.dir/src/lib/texture.cpp.o
.PHONY : src/lib/texture.cpp.o

src/lib/texture.i: src/lib/texture.cpp.i
.PHONY : src/lib/texture.i

# target to preprocess a source file
src/lib/texture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/texture.dir/build.make CMakeFiles/texture.dir/src/lib/texture.cpp.i
.PHONY : src/lib/texture.cpp.i

src/lib/texture.s: src/lib/texture.cpp.s
.PHONY : src/lib/texture.s

# target to generate assembly for a file
src/lib/texture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/texture.dir/build.make CMakeFiles/texture.dir/src/lib/texture.cpp.s
.PHONY : src/lib/texture.cpp.s

src/math/math.o: src/math/math.cpp.o
.PHONY : src/math/math.o

# target to build an object file
src/math/math.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/math.dir/build.make CMakeFiles/math.dir/src/math/math.cpp.o
.PHONY : src/math/math.cpp.o

src/math/math.i: src/math/math.cpp.i
.PHONY : src/math/math.i

# target to preprocess a source file
src/math/math.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/math.dir/build.make CMakeFiles/math.dir/src/math/math.cpp.i
.PHONY : src/math/math.cpp.i

src/math/math.s: src/math/math.cpp.s
.PHONY : src/math/math.s

# target to generate assembly for a file
src/math/math.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/math.dir/build.make CMakeFiles/math.dir/src/math/math.cpp.s
.PHONY : src/math/math.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... engine"
	@echo "... entity"
	@echo "... game"
	@echo "... geralt_eats"
	@echo "... lemmings"
	@echo "... math"
	@echo "... physics"
	@echo "... ray"
	@echo "... render_2D"
	@echo "... spectrum"
	@echo "... texture"
	@echo "... transform"
	@echo "... src/engine/engine.o"
	@echo "... src/engine/engine.i"
	@echo "... src/engine/engine.s"
	@echo "... src/engine/entity.o"
	@echo "... src/engine/entity.i"
	@echo "... src/engine/entity.s"
	@echo "... src/engine/game.o"
	@echo "... src/engine/game.i"
	@echo "... src/engine/game.s"
	@echo "... src/engine/physics.o"
	@echo "... src/engine/physics.i"
	@echo "... src/engine/physics.s"
	@echo "... src/engine/render_2D.o"
	@echo "... src/engine/render_2D.i"
	@echo "... src/engine/render_2D.s"
	@echo "... src/geometry/ray.o"
	@echo "... src/geometry/ray.i"
	@echo "... src/geometry/ray.s"
	@echo "... src/geometry/transform.o"
	@echo "... src/geometry/transform.i"
	@echo "... src/geometry/transform.s"
	@echo "... src/geralt_eats/geralt_eats.o"
	@echo "... src/geralt_eats/geralt_eats.i"
	@echo "... src/geralt_eats/geralt_eats.s"
	@echo "... src/lemmings/lemmings.o"
	@echo "... src/lemmings/lemmings.i"
	@echo "... src/lemmings/lemmings.s"
	@echo "... src/lib/spectrum.o"
	@echo "... src/lib/spectrum.i"
	@echo "... src/lib/spectrum.s"
	@echo "... src/lib/texture.o"
	@echo "... src/lib/texture.i"
	@echo "... src/lib/texture.s"
	@echo "... src/math/math.o"
	@echo "... src/math/math.i"
	@echo "... src/math/math.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

